build(package): save `@types/node` to fix typescript error
```
node_modules/@types/node/module.d.ts(121,13): error TS2386: Overload signatures must all be optional or required.
```